#' A NMAcompanion_wrapper that runs the entire pipeline
#'
#' @description Reads a tab-delimited nuclear morphology analysis (NMA) export file
#' and runs a full analysis of morphology data.
#'
#' @param path_to_export A string giving the file path to the tab-delimited NMA export file.
#'
#' @return A named list with six elements:
#' \describe{
#'   \item{\code{data}}{Raw dataset read via \code{\link{read_NMA_export}}}
#'   \item{\code{regions_of_interest}}{Regions of interest found using \code{\link{get_regions_of_interest}}}
#'   \item{\code{clustered_rois}}{Clustered ROIs returned by \code{\link{Cluster_ROI_list}}, with continuous clusters appended from \code{\link{find_contious_clusters}}}
#'   \item{\code{continuous_clusters}}{Output of \code{\link{find_contious_clusters}}}
#'   \item{\code{morphological_features}}{Extracted using \code{\link{Amalgamate_morphological_features}}}
#'   \item{\code{cluster_graph}}{Graph generated by \code{\link{Graph_clustered_ROIs}}}
#' }
#'
#' The function performs the following steps:
#' \enumerate{
#'   \item Loads the dataset from a path to a .txt file using \code{\link{read_NMA_export}}
#'   \item Identifies regions of interest via \code{\link{get_regions_of_interest}}
#'   \item Clusters regions using \code{\link{Cluster_ROI_list}} and finds continuous clusters via \code{\link{find_contious_clusters}}
#'   \item Extracts morphological features using \code{\link{Amalgamate_morphological_features}}
#'   \item Generates graphs with \code{\link{Graph_clustered_ROIs}}
#' }
#'
#' @examples
#' \dontrun{
#' data <- NMAcompanion_wrapper("data/NMA_output.txt")
#' }
#'
#' @export


NMAcompanion_wrapper<-function(path_to_export){
  data<-read_NMA_export(path_to_export)
  a <- get_regions_of_interest(data)
  b <- Cluster_ROI_list(a,allow_further_itteration = TRUE)
  c <- find_contious_clusters(data)
  b <- append(b, c)
  d <- Amalgamate_morphological_features(data, b)
  e <- Graph_clustered_ROIs(b, data)
  # Return the results as a named list
  return(list(
    data = data,
    regions_of_interest = a,
    clustered_rois = b,
    continuous_clusters = c,
    morphological_features = d,
    cluster_graph = e
  ))
}
